config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'wash_service', to: 'home#wash_service'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :vehicle
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :transactions, dependent: :destroy

  def car_wash
    5.00
  end

  def truck_wash
    10.00
  end

  def muddy_bed_upcharge
    truck_wash + 2.00
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/service_helper.rb
module ServiceHelper
  def check_plate_number
    if params[:plate_number] == '1111111'
      redirect_back fallback_location: root_path, alert: "Decline Service Reason: Vehicle Reported Stolen!"
    end
  end

  def check_if_bed_down
    if params[:bed_is_down?].present?
      redirect_back fallback_location: root_path, alert: "Decline Service Reason: Truck Bed Down!"
    end
  end

  def check_for_discount transaction
    if @vehicle.visit_count == 2
      transaction.total_price *= 0.50
      transaction.save
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ServiceHelper
  before_action :check_plate_number,
                :check_if_bed_down, only: :wash_service

  def index
  end

  def wash_service
    find_vehicle
    update_visit_counter
    transaction = Transaction.create(vehicle_id: @vehicle.id, plate_number: @vehicle.plate_number)
    determine_wash_price transaction
    @transactions = @vehicle.transactions.order('created_at DESC')
  end

  private

    def find_vehicle
      @vehicle = Vehicle.find_by(plate_number: params[:plate_number])
      if @vehicle.nil?
        @vehicle = Vehicle.create(vehicle_type: params[:vehicle_type],
                                  plate_number: params[:plate_number])
      end
    end

    def update_visit_counter
      if @vehicle.visit_count.blank?
        @vehicle.visit_count = 1
      elsif @vehicle.visit_count >= 1
        @vehicle.visit_count += 1
      end
      @vehicle.save
    end

    def determine_wash_price transaction
      if @vehicle.vehicle_type == "truck"
        transaction.total_price = params[:mud_in_bed?].present? ? @vehicle.muddy_bed_upcharge : @vehicle.truck_wash
      else
        transaction.total_price = @vehicle.car_wash
      end
      transaction.save
      check_for_discount transaction
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Car Wash</h1>
<% flash.each do |key, value| %>
  <div class="alert alert-danger" role="alert"><%= value %></div>
<% end %>


  <%= form_tag wash_service_path, method: 'post' do %>
    <div class="form-group col-md-12">
      <%= radio_button_tag(:vehicle_type, "car") %>
      <%= label_tag(:car, "Car ($5.00)") %>
    </div>
    <div class="form-group col-md-12">
      <%= radio_button_tag(:vehicle_type, "truck") %>
      <%= label_tag(:truck, "Truck ($10.00)") %>

      <div class="form-group col-md-12">
        <%= check_box_tag(:mud_in_bed?) %>
        <%= label_tag(:mud_in_bed?, "Is there mud in truck bed?") %>
      </div>
      <div class="form-group col-md-12">
        <%= check_box_tag(:bed_is_down?) %>
        <%= label_tag(:bed_is_down?, "Is the truck bed down?") %>
      </div>
    </div>
    <div class="form-group col-md-12">
      <%= label_tag(:plate_number, "Plate Number") %>
      <%= text_field_tag(:plate_number, nil, placeholder: "Enter Plate Number") %>
    </div>
    <div class="form-group col-md-12">
      <%= submit_tag "submit" %>
    </div>
  <% end %>

app/views/home/wash_service.html.erb
<h5><%= link_to "Back", root_path %></h5>

<h2>Transaction Info</h2>
<div class="col-md-12">
  <h5><%= "Vehicle type: #{@vehicle.vehicle_type}" %></h5>
  <h5><%= "Plate# #{@vehicle.plate_number}" %></h5>
  <h5><%= "Visits: #{@vehicle.visit_count}" %></h5>
</div>

<% @transactions.each do |transaction| %>
  <div>
    <h4>
      <em><%= local_time(transaction.created_at, '%B %e, %Y %l:%M%P') %></em>
      <%= "________" %>
      <%= number_to_currency(transaction.total_price) %>
    </h4>
  </div>
<% end %>

<h3>
  <%= "Total Sales: #{number_to_currency(@transactions.pluck(:total_price).sum)}" %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarWash</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>